### ISSUE TITLE
New deployment on heroku is getting application error

### ISSUE THREAD

**Issue by xiaopow** [madisvain/exchangeratesapi#114]
A fresh deployment of the app on heroku is showing Application Error. Running on heroku stack 20.

Server logs is showing a repeated error

```
asyncpg.exceptions.InvalidAuthorizationSpecificationError: no pg_hba.conf entry for host "xx.xx.xx.xxx", user "xxxxxxxxxxxx", database "xxxxxxxxxxxxx", SSL off
2021-03-07T13:32:43.043790+00:00 app[web.1]: [2021-03-07 13:32:43 +0000] [1654] [INFO] Worker exiting (pid: 1654)
2021-03-07T13:32:43.143064+00:00 app[web.1]: [2021-03-07 13:32:43 +0000] [1674] [INFO] Booting worker with pid: 1674
2021-03-07T13:32:43.233922+00:00 app[web.1]: [2021-03-07 13:32:43 +0000] [1675] [INFO] Booting worker with pid: 1675
2021-03-07T13:32:43.372120+00:00 app[web.1]: [2021-03-07 13:32:43 +0000] [1660] [ERROR] Exception in worker process
2021-03-07T13:32:43.372121+00:00 app[web.1]: Traceback (most recent call last):
2021-03-07T13:32:43.372122+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
2021-03-07T13:32:43.372123+00:00 app[web.1]:     worker.init_process()
2021-03-07T13:32:43.372123+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/sanic/worker.py", line 48, in init_process
2021-03-07T13:32:43.372124+00:00 app[web.1]:     super().init_process()
2021-03-07T13:32:43.372124+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 134, in init_process
2021-03-07T13:32:43.372125+00:00 app[web.1]:     self.run()
2021-03-07T13:32:43.372125+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/sanic/worker.py", line 64, in run
2021-03-07T13:32:43.372125+00:00 app[web.1]:     self.loop)
2021-03-07T13:32:43.372126+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/sanic/server.py", line 503, in trigger_events
2021-03-07T13:32:43.372126+00:00 app[web.1]:     loop.run_until_complete(result)
2021-03-07T13:32:43.372126+00:00 app[web.1]:   File "uvloop/loop.pyx", line 1448, in uvloop.loop.Loop.run_until_complete
2021-03-07T13:32:43.372127+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gino/ext/sanic.py", line 125, in before_server_start
2021-03-07T13:32:43.372127+00:00 app[web.1]:     loop=loop,
2021-03-07T13:32:43.372129+00:00 app[web.1]:   File "/app/exchangerates/utils.py", line 19, in set_bind
2021-03-07T13:32:43.372129+00:00 app[web.1]:     **kwargs
2021-03-07T13:32:43.372129+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gino/ext/sanic.py", line 143, in set_bind
2021-03-07T13:32:43.372130+00:00 app[web.1]:     return await super().set_bind(bind, loop=loop, **kwargs)
2021-03-07T13:32:43.372130+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gino/api.py", line 390, in set_bind
2021-03-07T13:32:43.372130+00:00 app[web.1]:     bind = await create_engine(bind, loop=loop, **kwargs)
2021-03-07T13:32:43.372131+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gino/strategies.py", line 42, in create
2021-03-07T13:32:43.372131+00:00 app[web.1]:     pool = await dialect.init_pool(u, loop)
2021-03-07T13:32:43.372131+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gino/dialects/asyncpg.py", line 315, in init_pool
2021-03-07T13:32:43.372132+00:00 app[web.1]:     **self._pool_kwargs)
2021-03-07T13:32:43.372132+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gino/dialects/asyncpg.py", line 210, in _init
2021-03-07T13:32:43.372133+00:00 app[web.1]:     self._pool = await asyncpg.create_pool(**args)
2021-03-07T13:32:43.372133+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/asyncpg/pool.py", line 398, in _async__init__
2021-03-07T13:32:43.372133+00:00 app[web.1]:     await self._initialize()
2021-03-07T13:32:43.372134+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/asyncpg/pool.py", line 415, in _initialize
2021-03-07T13:32:43.372134+00:00 app[web.1]:     await first_ch.connect()
2021-03-07T13:32:43.372139+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/asyncpg/pool.py", line 125, in connect
2021-03-07T13:32:43.372139+00:00 app[web.1]:     self._con = await self._pool._get_new_connection()
2021-03-07T13:32:43.372140+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/asyncpg/pool.py", line 461, in _get_new_connection
2021-03-07T13:32:43.372140+00:00 app[web.1]:     **self._connect_kwargs)
2021-03-07T13:32:43.372140+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/asyncpg/connection.py", line 1602, in connect
2021-03-07T13:32:43.372140+00:00 app[web.1]:     max_cacheable_statement_size=max_cacheable_statement_size)
2021-03-07T13:32:43.372140+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/asyncpg/connect_utils.py", line 426, in _connect
2021-03-07T13:32:43.372141+00:00 app[web.1]:     connection_class=connection_class)
2021-03-07T13:32:43.372141+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/asyncpg/connect_utils.py", line 402, in _connect_addr
2021-03-07T13:32:43.372141+00:00 app[web.1]:     await asyncio.wait_for(connected, loop=loop, timeout=timeout)
2021-03-07T13:32:43.372141+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
2021-03-07T13:32:43.372141+00:00 app[web.1]:     return fut.result()
2021-03-07T13:32:43.372149+00:00 app[web.1]: asyncpg.exceptions.InvalidAuthorizationSpecificationError: no pg_hba.conf entry for host "xx.xx.xx.xxx", user "xxxxxxxxxxxx", database "xxxxxxxxxxxxx", SSL off
```

**Comment by idogrosberg** [comment]
Hey @xiaopow,
The same thing happens to us, do you found any workaround?
